### ISSUE TITLE
protection class II toggle switches

### ISSUE THREAD

**Issue by flysch** [gonium/EVSE-Car-Simulator#2]
To minimize the risk of an electric shock please consider protection class II toggle switches, e.g.
https://www.reichelt.de/Switches-Rocker/KIPP-1824-1101/3/index.html?ACTION=3&LA=2&ARTICLE=154582&GROUPID=7584&artnr=KIPP+1824.1101&SEARCH=%252A

**Comment by gonium** [comment]
@flysch You're right, I added a note to the documentation. See the commit above.
