### ISSUE TITLE
existing/permanent Type 2 cable

### ISSUE THREAD

**Issue by No0ne** [gonium/EVSE-Car-Simulator#4]
How do the schematics need to be changed to work with an existing or permanent installed Type 2 cable e.g. ABB Terra 23 CJG, Tesla Wall Connector, etc?
How to deal with R3 in that case? I only managed to get a red status light out of my Tesla Wall Connector.

**Comment by gonium** [comment]
Sorry for my late reply - my notification settings apparently are messed up. For a type 2 cable, you need to buy a car outlet that matches the type 2 cable. If you have a good source for these outlets please let me know!

You don't need R3 - just leave it unconnected.

**Comment by No0ne** [comment]
Hi there, I still had no luck. Leaving R3 disconnect didn't work either. As soon as I turn on both EV detect+ready the wall connector status turns red. The connector is definitely working, charged a Model X and an Ioniq with it. I'll continue debugging this with voltage and resistance measurements.

**Comment by No0ne** [comment]
I found the solution, just wait **10 sec.** before going from **EV detect** to **EV ready** as explained here: https://teslamotorsclub.com/tmc/posts/2203495/

**Comment by gonium** [comment]
Thanks for letting me know!
